### ISSUE TITLE
GitHub TOS issues with license

### ISSUE THREAD

**Issue by bb010g** [BeardDesign1/Material-design-theme-ressources#12]
Your current license is:

> Lilian Tedone(Beard Design) retains full copyright of this code.
> You are NOT ALLOWED to redistribute this file/Theme or any of the contents of it in any way or method.
> You are allowed to use this theme as it is, and edit it it AS LONG AS YOU KEEP IT FOR YOURSELF.
> I.e. you are NOT ALLOWED to post an edited version of this theme to Github or other similar platforms without a clear and direct permission from Lilian Tedone.
> Sorry I have to be super aggressive in this legal stuff, but there has been some problems and I just dont want more :3

However, the [GitHub TOS § D.5](https://help.github.com/articles/github-terms-of-service/#5-license-grant-to-other-users) (License Grant to Other Users) says:

> Any User-Generated Content you post publicly, including issues, comments, and contributions to other Users' repositories, may be viewed by others. By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control).
> 
> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking). You may grant further rights if you [adopt a license](https://help.github.com/articles/adding-a-license-to-a-repository/#including-an-open-source-license-in-your-repository). If you are uploading Content you did not create or own, you are responsible for ensuring that the Content you upload is licensed under terms that grant these permissions to other GitHub Users.

Your requirement to not fork and change this code without your express permission goes against GitHub's requirement that you allow users to fork and change your public code without your express permission.

I would personally recommend choosing an [actual license](https://choosealicense.com/) over your current custom one. Given how you seem to be worried about people stealing your code without attribution, the [GPLv3](https://choosealicense.com/licenses/gpl-3.0/) may be a good choice.

**Comment by BeardDesign1** [comment]
Hi, I wrote that whole thing about a year ago, when someone started posting the theme as their own, it was more to scare someone who might want to do the same thing, I know that it doesn't have any legal value and goes against tos. So yeah I guess you're right, I should remove this and use an actual license, thanks ^^

**Comment by Alipoodle** [comment]
Also as note:

Forking a github repo will still credit the original repo in the top left corner where the repo name is. Compared to what I assume was intended that people just reupload the theme as their own, by not forking it!

But I do understand why a real license should be used, as it makes it a lot clearer!

**Comment by bb010g** [comment]
Bump about the old license still being here.

**Comment by zerebos** [comment]
This depends on the interpretation.

From Beard's original license it says

> you are NOT ALLOWED to **post** an edited version of this theme to Github or other similar platforms without a clear and direct permission from Lilian Tedone.

In this phrase "post" can be taken to mean create their own repository and upload the same code *without* forking the original. This is an allowed denial by GitHub ToS because **forking** is a GitHub function which is expressly permitted by the ToS. In fact this is the phrasing they use themselves in the ToS.

> You retain ownership of and responsibility for Content you create or own ("Your Content"). If you're **posting** anything you did not create yourself or do not own the rights to, you agree that you are responsible for any Content you **post**; that you will only submit Content that you have the right to post; and that you will fully comply with any third party licenses relating to Content you post.

So reposting itself is prohibited by GitHub ToS anyways and could count as redistribution which is also inherently denied in the original license. Forking is not necessarily interpreted as redistribution because it is essentially a clone linking back to the original.

You said 
> Your requirement to not fork and **change** this code without your express permission goes against GitHub's requirement that you allow users to fork and change your public code without your express permission.

Here you say that requesting users to not modify the code without permission is against GitHub's ToS. However they do not expressly say modifications, in fact they say this:
> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking).

None of the words there constitute a right to modify. Display, perform, and reproduce through forking do not inherently grant modification rights. In fact there are many publicly viewable repos which expressly deny modifications but can be forked as per the ToS. Granted, this is up for interpretation as to whether being allowed to fork also allows modifications, but it does not expressly state that in the ToS.

Regardless of this however, your claim was that Beard's license did not allow any modifications which is not true. It said:
> You are allowed to use this theme as it is, and edit it it AS LONG AS YOU KEEP IT FOR YOURSELF.
I.e. you are NOT ALLOWED to post an edited version of this theme to Github or other similar platforms without a clear and direct permission from Lilian Tedone.

So the license itself says edits are allowed for personal use but not in redistribution, which I already went over above as to how it does not break ToS.


Although I do not find Lilian's license to be ToS-breaking, I think it is—at best—unclear, and an alternate with improved and clearer language should be used in its stead. This could help prevent issues like this one, but moreover could also help in deterring malicious persons from attempting to pass off Lilian's work as their own.

**Comment by zerebos** [comment]
I talked to GitHub and they said that license is fine, but Beard decided to remove it anyways so it is a non-issue.
